apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Say Hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
  test:
    steps:
      - name: Checkout Repository
        uses: cloudbees-io/checkout@v1
      - name: Publish Jest Test Results
        uses: cloudbees-io/publish-test-results@v1
        kind: test
        with:
          test-type: JEST
          folder-name: ${{ cloudbees.workspace }}/coverage/*/*/jest-results.json
