apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Say Hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
      - name: Checkout Repository
        uses: cloudbees-io/checkout@v1
      - name: Publish Passed Jest Test Results Only
        if: ${{always()}}
        uses: cloudbees-io/publish-test-results@v1
        with:
          test-type: jest
          folder-name: ${{ cloudbees.workspace }}/passed-jest-results.json
      - name: Publish Passed And Failed Jest Test Results
        if: ${{always()}}
        uses: cloudbees-io/publish-test-results@v1
        with:
          test-type: jest
          folder-name: ${{ cloudbees.workspace }}/failed-jest-results.json
  test:
    steps:
      - uses: cloudbees-io/publish-test-results@v1
        name: Publish Jest Test Results
        kind: test
        with:
          test-type: JEST
          folder-name: passed-test-results.json
