apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch: {}
jobs:
  build:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo "hello world"
    needs: scan
  scan:
    steps:
      - uses: cloudbees-io/trufflehog-secret-scan-code@v1
        name: TruffleHog Secrets Scan
        kind: scan
        with:
          repoUrl: https://github.com/dianaprince9g/superman
          branch: main
          token: ${{ secrets.TOKEN }}
  test:
    steps:
      - name: Trigger Github job using Cloudbees Github Action -  test
        uses: cloudbees-io/ghactions-run-workflow@v2
        kind: build
        with:
          url: https://api.github.com/
          token: ${{ secrets.TOKEN }}
          org-name: dianaprince9g
          repo-name: superman
          workflow-name: 'Build_Test_Deploy'
          parameters: '{"param1":"this is with space"}'
          branch-name: main