apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"

      - name: Trufflehog Secret Scan
        uses: cloudbees-io/trufflehog-secret-scan-code@v1
        with:
          repoUrl: https://github.com/jsayerascb/test
          branch: main
          token: ${{ secrets.TOKEN }}
