apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch: {}
jobs:
  build:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo "hello world"
          echo "api.url: ${{ cloudbees.api.url }}"
          echo "home: ${{ cloudbees.home }}"
          echo "Job ID: ${{ job.id }}"
          echo "run_id: ${{ cloudbees.run_id }}"
          echo "Event Sender: ${cloudbees.event.sender}"
    needs: scan
  scan:
    steps:
      - uses: cloudbees-io/trufflehog-secret-scan-code@v1
        name: TruffleHog Secrets Scan
        kind: scan
        with:
          repoUrl: https://github.com/dianaprince9g/superman
          branch: main
          token: ${{ secrets.TOKEN }}
