apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Say Hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
  test:
    steps:
      - name: Run Jenkins job
        uses: cloudbees-io/jenkins-run-job@v2
        with:
          username: ${{ secrets.JENKINS_USERNAME }}
          token: ${{ secrets.JENKINS_PASSWORD }}
          url: ${{ vars.JENKINS_URL }}
          job-name: my-platform-job
          parameters: '{"ENV_NAME":"TEST"}'
