name: servicnow-create-approve-close-workflow
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
on:
  push:
    branches:
      - '**'

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  create-approve-close-servicenow-job:
    steps:
      - id: servicenow-create
        name: Trigger Servicenow Create Mode
        uses: cloudbees-io/servicenow@v1
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ secrets.SERVICENOW_USERNAME }}
          password: ${{ secrets.SERVICENOW_PASSWORD }}
          action-type: "create"
          cr-type: "normal"
          short-description: "BT Demo create normal"